import random

def get_random_message():
    quotes = [
        "The roots of resilience grow strongest in the darkest soil. Embrace your struggles, for they nourish the strength you need to blossom.",
        "Like a sculptor chiseling a masterpiece, challenges shape you into your most magnificent form. Endure the process, and emerge stronger and more beautiful than before.",
        "Every tear is a baptism of fire, forging your spirit into unyielding steel. Let your tears cleanse and harden you, ready to face any storm.",
        "Doubt may whisper its negativity, but faith roars its defiance. Choose faith as your weapon, and silence the voice of fear with your unwavering belief.",
        "Trust in the Lord and do good; so you will dwell in the land and enjoy security. Psalm 37:3",
        "God is our refuge and strength, a very present help in trouble. Psalm 46:1",
        "Call on me in the day of trouble; I will deliver you, and you shall glorify me. Psalm 50:15",
        "Those who love me I will deliver; I will protect those who know my name. Psalm 91:14",
        "Trust in him and he will help you; make your ways straight and hope in him. Sirach:2:6",
        "My child, when you come to serve the Lord, prepare yourself for testing. Sirach 2:1",
        "Mistakes are not flaws, they are brushstrokes on the canvas of your life. Learn from them, adjust your colors, and paint a masterpiece of resilience.",
        "Be the bridge that connects islands of thought, not the wall that divides them. Embrace diversity, build bridges of understanding, and watch the world unite.",
        "Like spices in a dish, differences add flavor and richness to life. Celebrate the unique ingredients of humanity, and savor the symphony of their blend.",
        "Judging others is a mirror reflecting your own insecurities. Let go of judgment, embrace acceptance, and watch your own inner light shine brighter.",
        "Perfection is a mirage, beauty lies in embracing the imperfections that make us unique. Celebrate your individuality, and let your colors shine.",
        "Silence the voices of division, amplify the whispers of unity. Be the voice that breaks down walls and builds bridges of acceptance.",
        "Your dreams are not just wishes, they are blueprints for your future. Dare to architect your life with ambition, and watch your dreams take form.",
        "The impossible is just a dare waiting to be accepted. Take the leap, defy the odds, and rewrite the definition of what's possible with your audacious spirit.",
        "Fear may hold you back, but curiosity beckons you forward. Embrace the unknown, explore the untrodden paths, and discover the boundless possibilities that lie beyond your comfort zone.",
        "The universe whispers your potential, listen with your heart and translate its language into action. Your dreams are waiting to be manifested, so take the first step and watch them unfold.",
        "Gratitude is the magnet that attracts blessings. Open your heart to appreciate the little things, and watch abundance flow into your life.",
        "Laughter is the music of the soul, share it generously and watch joy ripple outwards, filling the world with its melody.",
        "Kindness is not a weakness, it's a superpower. Use it to heal wounds, mend bridges, and build a world filled with compassion.",
        "Silence is not emptiness, it's the fertile ground where wisdom whispers. Listen deeply to its secrets, and let your intuition guide you.",
        "Leave your footprints on the sands of time, not with your achievements, but with the love and light you shared with the world.",
        "The fiercest flames forge the strongest steel. Let your challenges be the fire that tempers your spirit into unwavering strength.",
        "Every tear carves a path to resilience, every scar a testament to your victories over adversity. Wear them with pride, for they tell the story of your courage.",
        "Darkness only reveals the brilliance of your inner light. Embrace the shadows, for they guide you to your own fire.",
        "Doubt whispers, 'You can't,' but hope roars, 'Try!' Let hope be your compass through the storms, and watch the impossible become possible.",
        "Mistakes are stepping stones to wisdom, not roadblocks to success. Learn from them, adjust your course, and rise with renewed determination.",
        "Be the rainbow that paints the sky after the storm. Embrace diversity, celebrate differences, and let your kindness bridge the gaps between us.",
        "Like flowers in a meadow, each soul blooms in its unique way. Appreciate the vibrant tapestry of humanity, and let your garden be a haven of acceptance.",
        "When they call to me, I will answer them; I will be with them in trouble, I will rescue them and honor them. Psalm 91:15",
        "May he grant you your heart's desire and fulfill all your plans. Psalm 20:4",
        "The Lord answer you in the day of trouble. The name of the God of Jacob protect you. Psalm 20:1",
        "The Lord is near to the brokenhearted and saves the crushed in spirit. Psalm 34:18",
        "Surely God is my salvation; I will trust and will not be afraid, for the Lord God is my strength and my might; he has become my salvation. Isaiah 12:2",
        "O Lord, you are my God; I will exalt you, I will praise your name; For you have done wonderful things, plans formed of old, faithful and sure. Isaiah 25:1",
        "Do not fear, for I have redeemed you; I have called you by name, You are mine. Isaiah 43:5",
        "Thus says the Lord who made you, who formed you in the womb and will help you. Isaiah 44:2",
        "Judging others only dims your own light. Let understanding be your torch, illuminating the path towards unity and belonging.",
        "Differences are not weaknesses, but threads that weave the rich tapestry of life. Embrace them, learn from them, and strengthen the fabric of humanity.",
        "Silence the voices of division, amplify the whispers of connection. Be the voice that calls for understanding, and watch walls crumble into bridges.",
        "Your dreams are not just wishes, they are whispers of your potential. Listen closely, nurture them with passion, and watch them take flight.",
        "The impossible is just a dare waiting to be accepted. Take the leap, defy limitations, and rewrite the definition of what's possible with your audacity.",
        "Gratitude unlocks the door to abundance. Open your heart to appreciate the simple joys, and watch your life overflow with blessings.",
        "Laughter is the music of the soul, share it freely and watch joy ripple outwards, filling the world with its melody.",
        "Kindness is a boomerang that returns with blessings. Be the source of compassion, and watch the world become a kinder place.",
        "Silence is not emptiness, it's the fertile ground where creativity blooms. Listen deeply to its whispers, and let your imagination take flight.",
        "Leave your footprints on the sands of time, not with your achievements, but with the love and light you brought to the world.",
        "The greatest oak started as a tiny seed weathering storms. Embrace your challenges, for they are the soil from which your resilience grows.",
        "Do not fear, for you will not be ashamed. Isaiah 54:4",
        "Do not be afraid of them, for I am with you to deliver you, says the Lord. Jeremiah 1:8",
        "I will not look on you in anger, for I am merciful, says the Lord; I will not be angry forever. Jeremiah 3:12",
        "May the God of hope fill you with all joy and peace. Romans 15:13",
        "And remember, I am with you always to the end of age. St Mark",
        "The spirit helps us in our weakness. Romans 8:26",
        "Who will separate us from the love of Christ? Will hardship, distress, persecution, or famine, or nakedness, or peril, or sword? Romans 8:35",
        "Like stars in a vast sky, each soul shines with its unique brilliance. Embrace the diversity, and watch the tapestry of humanity become a breathtaking masterpiece.",
        "Your dreams are not just pictures on a wall, they are blueprints for your life. Take the paintbrush of your ambition, and bring them to life on the canvas of reality.",
        "Laughter is the sunshine that melts away the ice of fear. Share it generously, and watch the world blossom with joy.",
        "Leave your mark on the world, not with your achievements, but with the kindness and compassion you spread. Be the light that inspires others to shine.",
        "Storms forge the mightiest oaks, let your struggles sculpt your strength.",
        "Every tear carves a path to resilience, every scar a testament to your fight.",
        "Darkness only reveals the brilliance of your inner light. Embrace the shadows, they guide you to your fire.",
        "Doubt whispers, 'You can't,' but hope roars, 'Try!' Let hope be your compass through the storms.",
        "Fall down seven times, rise eight. Each stumble teaches you the dance of victory.",
        "Be the rainbow in someone's gray sky, the melody in their silence, the color in their monochrome world.",
        "Differences are not walls, but bridges. Build understanding, not prejudice, and watch hearts connect.",
        "Like spices in a dish, diversity adds richness to life. Embrace the unique flavors, and savor the tapestry of humanity.",
        "Judging dims your own light, acceptance ignites a symphony of understanding. Choose to illuminate, not extinguish.",
        "The world is a vibrant canvas, and every soul a unique brushstroke. Together, we paint a masterpiece of unity.",
        "Dreams are not luxuries, they are blueprints for your soul. Dare to dream big, and build your life with stardust.",
        "The impossible is just a dare waiting to be accepted. Take the leap, chase the stars, and rewrite the definition of 'impossible.'",
        "Every step towards your dream is a victory dance. Celebrate the journey, for it's paved with lessons and triumphs.",
        "Doubt is the dust on your wings, fear the rust on your compass. Cleanse your spirit, let your dreams soar.",
        "The universe whispers your potential, listen closely. Believe in the magic within, and watch your dreams take flight.",
        "Life is a dance between laughter and tears. Embrace the rhythm, find your balance, and move with grace.",
        "Gratitude is the key that unlocks the abundance of life. Open your heart, count your blessings, and watch joy overflow.",
        "Kindness is the language of the universe, spoken in gentle smiles and helping hands. Let your words and actions be a symphony of compassion.",
        "Silence is not emptiness, it's the fertile ground where wisdom whispers. Listen deeply, for it holds the secrets of your soul.",
        "Leave your footprints on the sands of time, not with your achievements, but with the kindness you inspired in others.",
        "The fiercest storms reveal the strongest anchors. Let your faith and courage be your anchor in any turbulence.",
        "Every obstacle is a chance to rise above. See challenges as stepping stones, not roadblocks, and climb towards your summit.",
        "Tears water the seeds of resilience, let them nourish your strength and bloom into beautiful determination.",
        "Fear is a paper tiger, easily burned by the fire of your will. Don't let it intimidate you, step into its flames and emerge stronger.",
        "Mistakes are not failures, they are lessons in disguise. Embrace them, learn from them, and rise with renewed wisdom.",
        "Be the bridge that connects, not the wall that divides. Embrace differences, learn from each other, and build a world of understanding.",
        "Like flowers in a meadow, each soul blooms in its unique way. Celebrate the diversity, and let your garden be a symphony of acceptance.",
        "Judging others only dims your own light. Let kindness be your torch, illuminating the path towards unity and belonging.",
        "True beauty lies not in conformity, but in the authenticity of each soul. Embrace your individuality, and let your colors shine.",
        "Open your mind and heart to the tapestry of humanity. Every thread adds richness to the fabric, appreciate them all.",
        "Your dreams are not fantasies, they are whispers of your potential. Listen closely, nurture them, and watch them manifest into reality.",
        "The only limit to your possibilities is the one you set for yourself. Push past self-doubt, embrace the unknown, and discover your boundless potential.",
        "Every small step towards your dream is a victory lap. Celebrate the journey, for it's paved with lessons and triumphs that lead to your destination.",
        "Fear may whisper doubt, but hope roars encouragement. Let hope be your compass, and navigate towards the stars of your dreams.",
        "The universe whispers your potential, but it's up to you to listen. Tune in to your inner voice, and let it guide you towards your magnificent possibilities.",
        "The greatest gift you can give yourself is the permission to be happy. Choose joy, embrace laughter, and let your heart sing.",
        "Live your life in full color, not shades of gray. Embrace the adventures, the challenges, and the beauty of every moment.",
        "Silence is not emptiness, it's the fertile ground where creativity blooms. Listen to the whispers within, and let your imagination take flight.",
        "Kindness is a boomerang that returns with blessings. Let your actions ripple outwards, and watch the world become a kinder place.",
        "Leave your footprints on the sands of time, not with your achievements, but with the love and compassion you inspired in others.",
        "The darkest nights reveal the brilliance of the stars. Embrace the darkness, for it guides you to your inner light.",
        "Blessed are the pure in heart, for they will see God. Matthew 5:8",
        "If we live by the spirit, let us also be guided by the spirit. Ephesians 5:25",
        "Therefore whoever wishes to be a friend of the world becomes an enemy of God. James 4:4",
        "Whoever does not love does not know God, for God is love. John 4:8",
        "Blessed are the poor in spirit, for theirs is the kingdom of heaven. Matthew 5:3",
        "Blessed are the peacemakers, for they will be called children of God. Matthew 5:9",
        "Their ways are always known to him; they will not be hid from his eyes. Sirach 17:15",
        "Before you speak, learn, and before you fall ill, take care of your health. Sirach 18:19",
        "Every tear is a testament to your courage, every scar a badge of your resilience. Wear them with pride, for they tell the story of your strength.",
        "Like a phoenix rising from the ashes, let your challenges become the fuel for your transformation. Emerge stronger, wiser, and more beautiful than before.",
        "Doubt may whisper its doubts, but hope sings its song of possibilities. Let hope be your anthem, and silence the voice of fear.",
        "Challenges are not roadblocks, but detours on your journey. Embrace the detour, learn its lessons, and find the scenic route to your destination.",
        "Like notes in a symphony, each soul contributes to the harmony of life. Listen to their unique melodies, and together, create a masterpiece of understanding.",
        "Judging others is like dimming your own light. Let kindness be your beacon, illuminating the path towards unity and connection.",
        "Differences are not weaknesses, but strengths that enrich the tapestry of humanity. Appreciate the diverse threads, and let them weave a world of tolerance and respect.",
        "Be the rain that waters the garden of diversity, not the wind that scatters its seeds. Foster understanding, and watch acceptance bloom.",
        "Embrace the beauty of imperfection, for it is in our differences that we find the most captivating stories and the truest connections.",
        "Your dreams are not just wishes, they are blueprints for your future. Dare to design your life with ambition, and watch your dreams become reality.",
        "The impossible is just a dare waiting to be accepted. Take the leap, defy the odds, and rewrite the definition of what's possible.",
        "Every step towards your dream, no matter how small, is a victory march. Celebrate the journey, for it's paved with milestones and lessons that lead you closer to your goals.",
        "Fear may hold you back, but curiosity can set you free. Embrace the unknown, explore, and discover the boundless possibilities that lie beyond your comfort zone.",
        "The universe whispers your potential, listen with your heart and translate its language into action. Your dreams are waiting to be manifested.",
        "Like a mighty oak weathering the storm, let your inner strength rise to meet any challenge. Remember, the toughest trees bear the sweetest fruit.",
        "Every crack in the pavement offers a chance for a flower to bloom. Embrace your struggles as fertile ground for growth and resilience.",
        "The scars you carry are not wounds, but maps of your courage. They tell the story of your strength and the battles you've overcome.",
        "Don't fear the darkness, for it's within that you discover the power of your own inner light. Let your challenges illuminate your hidden potential.",
        "Challenges are not roadblocks, but stepping stones. Each hurdle you conquer builds the bridge to your dreams.",
        "The world is a vibrant tapestry woven with threads of diverse experiences. Embrace each color, each texture, for in their unity lies true beauty.",
        "Like snowflakes, no two stories are alike. Celebrate the unique melody each soul plays, and let their harmony enrich your own.",
        "Open your mind and heart to the symphony of differences. In the language of acceptance, you'll find the rhythm of unity and belonging.",
        "My child, from your youth choose discipline, and when you have grey hair, you will still find wisdom. Sirach 6:18",
        "To fear the Lord is fullness of wisdom. Sirach 1:16",
        "All wisdom is from the Lord and with him, it remains forever. Sirach 1:1",
        "I will be glad and exult in you; I will praise your name, O most high. Psalm 9:2",
        "Be strong and let your heart take courage, all you who wait for the Lord. Psalm 31:24",
        "O Lord, my God, I cry to you for help, and you have healed me. Psalm 30:2",
        "Judging others dims your own light. Let acceptance be your torch, illuminating the path to a world where everyone shines.",
        "The greatest gift you can offer is the gift of understanding. Listen without judgment, embrace differences, and watch the walls of division crumble.",
        "Your dreams are not just wishes, they are whispers of your potential. Dare to listen, dare to believe, and dare to chase them with the wings of your ambition.",
        "The stars may seem distant, but they are not out of reach. Aim high, reach for the impossible, and trust the magic that unfolds when you embrace the unknown.",
        "Every step towards your dream, no matter how small, is a victory lap around the stadium of your own potential. Celebrate each milestone, big or small.",
        "The only limit to your possibilities is the limit you place on yourself. Break free from self-doubt, embrace the power of \"what if,\" and watch your dreams take flight.",
        "Fear is just a paper dragon, easily burned by the fire of your determination. Don't let it hold you back. Embrace the possibilities, and watch your dreams become reality."
    ]
    return random.choice(quotes)



